server:
  port: 8080
  servlet:
    context-path: /duythuc

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/movie_ticket"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh


  mail:
    host: smtp.gmail.com
    port: 587
    username: duythuc08tt@gmail.com        # Thay b?ng Gmail c?a b?n
    password: zltlomhbtbyskmpp    # Thay b?ng App Password (b?t 2FA)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com


#JWT secret key
jwt:
  signerKey: "ktWvH+jVekZ1QVSc7imoQ0BmDed+jtf4wRlhq/U+2ctBDgk8kgtuMVe+9xS8Csxv"

#Cloudinary
cloudinary:
  cloud_name: "dmwcvykjn"
  api_key: "777287143839166"
  api_secret: "oEUE763pY2TgIXimgf9P_il6c9Q"



